//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HFDesk.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HFDesk.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 产品类型不能为空.
        /// </summary>
        internal static string strPrompt01 {
            get {
                return ResourceManager.GetString("strPrompt01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 电池日期不能为空.
        /// </summary>
        internal static string strPrompt02 {
            get {
                return ResourceManager.GetString("strPrompt02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 包装时间不能为空.
        /// </summary>
        internal static string strPrompt03 {
            get {
                return ResourceManager.GetString("strPrompt03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pmax不能为空.
        /// </summary>
        internal static string strPrompt04 {
            get {
                return ResourceManager.GetString("strPrompt04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voc不能为空.
        /// </summary>
        internal static string strPrompt05 {
            get {
                return ResourceManager.GetString("strPrompt05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vpm不能为空.
        /// </summary>
        internal static string strPrompt06 {
            get {
                return ResourceManager.GetString("strPrompt06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ipm不能为空.
        /// </summary>
        internal static string strPrompt07 {
            get {
                return ResourceManager.GetString("strPrompt07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isc不能为空.
        /// </summary>
        internal static string strPrompt08 {
            get {
                return ResourceManager.GetString("strPrompt08", resourceCulture);
            }
        }
    }
}
