//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5420
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IRFIDService
{
    
    void writeTag();
    
    void WriteLog(object[] parms);
    
    void readTag();
    
    ModuleInfo getModuleInfo(object[] parms);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="writeTag", Namespace="http://www.hulisoft.com/RFIDService")]
public partial class writeTagRequest
{
    
    public writeTagRequest()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="writeTagResponse", Namespace="http://www.hulisoft.com/RFIDService")]
public partial class writeTagResponse
{
    
    public writeTagResponse()
    {
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hulisoft.com/RFIDServiceData")]
public partial class ModuleInfo
{
    
    private string cellDateField;
    
    private string cellsourceField;
    
    private string eLGradeField;
    
    private string eqpIDField;
    
    private string ffField;
    
    private string iVFilePathField;
    
    private string ipmField;
    
    private string iscField;
    
    private string module_IDField;
    
    private string packedDateField;
    
    private string palletNOField;
    
    private string pivfField;
    
    private string pmaxField;
    
    private string productTypeField;
    
    private string statusField;
    
    private string vocField;
    
    private string vpmField;
    
    private bool b_writenDataBeforeField;
    
    private bool b_writenDataBeforeFieldSpecified;
    
    private string cell_mfg_dateField;
    
    private string cell_mfg_nameField;
    
    private string cell_supplier_countryField;
    
    private string customerField;
    
    private string iec_dateField;
    
    private string iec_verfyField;
    
    private string isoField;
    
    private string iso_14000_dateField;
    
    private string iso_14000_nameField;
    
    private string iso_9000_dateField;
    
    private string iso_9000_nameField;
    
    private string max_system_voltageField;
    
    private string mfg_countryField;
    
    private string mfg_nameField;
    
    private string polarity_of_terminalField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
    public string CellDate
    {
        get
        {
            return this.cellDateField;
        }
        set
        {
            this.cellDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
    public string Cellsource
    {
        get
        {
            return this.cellsourceField;
        }
        set
        {
            this.cellsourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
    public string ELGrade
    {
        get
        {
            return this.eLGradeField;
        }
        set
        {
            this.eLGradeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
    public string EqpID
    {
        get
        {
            return this.eqpIDField;
        }
        set
        {
            this.eqpIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
    public string FF
    {
        get
        {
            return this.ffField;
        }
        set
        {
            this.ffField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
    public string IVFilePath
    {
        get
        {
            return this.iVFilePathField;
        }
        set
        {
            this.iVFilePathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
    public string Ipm
    {
        get
        {
            return this.ipmField;
        }
        set
        {
            this.ipmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
    public string Isc
    {
        get
        {
            return this.iscField;
        }
        set
        {
            this.iscField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
    public string Module_ID
    {
        get
        {
            return this.module_IDField;
        }
        set
        {
            this.module_IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
    public string PackedDate
    {
        get
        {
            return this.packedDateField;
        }
        set
        {
            this.packedDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
    public string PalletNO
    {
        get
        {
            return this.palletNOField;
        }
        set
        {
            this.palletNOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
    public string Pivf
    {
        get
        {
            return this.pivfField;
        }
        set
        {
            this.pivfField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
    public string Pmax
    {
        get
        {
            return this.pmaxField;
        }
        set
        {
            this.pmaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
    public string ProductType
    {
        get
        {
            return this.productTypeField;
        }
        set
        {
            this.productTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
    public string Status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
    public string Voc
    {
        get
        {
            return this.vocField;
        }
        set
        {
            this.vocField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
    public string Vpm
    {
        get
        {
            return this.vpmField;
        }
        set
        {
            this.vpmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=17)]
    public bool b_writenDataBefore
    {
        get
        {
            return this.b_writenDataBeforeField;
        }
        set
        {
            this.b_writenDataBeforeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool b_writenDataBeforeSpecified
    {
        get
        {
            return this.b_writenDataBeforeFieldSpecified;
        }
        set
        {
            this.b_writenDataBeforeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
    public string cell_mfg_date
    {
        get
        {
            return this.cell_mfg_dateField;
        }
        set
        {
            this.cell_mfg_dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
    public string cell_mfg_name
    {
        get
        {
            return this.cell_mfg_nameField;
        }
        set
        {
            this.cell_mfg_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
    public string cell_supplier_country
    {
        get
        {
            return this.cell_supplier_countryField;
        }
        set
        {
            this.cell_supplier_countryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
    public string customer
    {
        get
        {
            return this.customerField;
        }
        set
        {
            this.customerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
    public string iec_date
    {
        get
        {
            return this.iec_dateField;
        }
        set
        {
            this.iec_dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
    public string iec_verfy
    {
        get
        {
            return this.iec_verfyField;
        }
        set
        {
            this.iec_verfyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
    public string iso
    {
        get
        {
            return this.isoField;
        }
        set
        {
            this.isoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
    public string iso_14000_date
    {
        get
        {
            return this.iso_14000_dateField;
        }
        set
        {
            this.iso_14000_dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=26)]
    public string iso_14000_name
    {
        get
        {
            return this.iso_14000_nameField;
        }
        set
        {
            this.iso_14000_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
    public string iso_9000_date
    {
        get
        {
            return this.iso_9000_dateField;
        }
        set
        {
            this.iso_9000_dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
    public string iso_9000_name
    {
        get
        {
            return this.iso_9000_nameField;
        }
        set
        {
            this.iso_9000_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=29)]
    public string max_system_voltage
    {
        get
        {
            return this.max_system_voltageField;
        }
        set
        {
            this.max_system_voltageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=30)]
    public string mfg_country
    {
        get
        {
            return this.mfg_countryField;
        }
        set
        {
            this.mfg_countryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
    public string mfg_name
    {
        get
        {
            return this.mfg_nameField;
        }
        set
        {
            this.mfg_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=32)]
    public string polarity_of_terminal
    {
        get
        {
            return this.polarity_of_terminalField;
        }
        set
        {
            this.polarity_of_terminalField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="WriteLog", Namespace="http://www.hulisoft.com/RFIDService")]
public partial class WriteLogRequest
{
    
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Namespace="http://www.hulisoft.com/RFIDService", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public object[] parms;
    
    public WriteLogRequest()
    {
    }
    
    public WriteLogRequest(object[] parms)
    {
        this.parms = parms;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="WriteLogResponse", Namespace="http://www.hulisoft.com/RFIDService")]
public partial class WriteLogResponse
{
    
    public WriteLogResponse()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="readTag", Namespace="http://www.hulisoft.com/RFIDService")]
public partial class readTagRequest
{
    
    public readTagRequest()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="readTagResponse", Namespace="http://www.hulisoft.com/RFIDService")]
public partial class readTagResponse
{
    
    public readTagResponse()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="getModuleInfo", Namespace="http://www.hulisoft.com/RFIDService")]
public partial class getModuleInfoRequest
{
    
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Namespace="http://www.hulisoft.com/RFIDService", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public object[] parms;
    
    public getModuleInfoRequest()
    {
    }
    
    public getModuleInfoRequest(object[] parms)
    {
        this.parms = parms;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="getModuleInfoResponse", Namespace="http://www.hulisoft.com/RFIDService")]
public partial class getModuleInfoResponse
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://www.hulisoft.com/RFIDService", Order=0)]
    public ModuleInfo getModuleInfoResult;
    
    public getModuleInfoResponse()
    {
    }
    
    public getModuleInfoResponse(ModuleInfo getModuleInfoResult)
    {
        this.getModuleInfoResult = getModuleInfoResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class RFIDServiceClient : Microsoft.Tools.ServiceModel.CFClientBase<IRFIDService>, IRFIDService
{
    
    public static System.ServiceModel.EndpointAddress EndpointAddress = new System.ServiceModel.EndpointAddress("http://larry-pc:8106/RFID.svc");
    
    public RFIDServiceClient() : 
            this(CreateDefaultBinding(), EndpointAddress)
    {
    }
    
    public RFIDServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
        addProtectionRequirements(binding);
    }
    
    private writeTagResponse writeTag(writeTagRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://www.hulisoft.com/RFIDService/IRFIDService/writeTag";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://www.hulisoft.com/RFIDService/IRFIDService/writeTagResponse";
        info.ResponseIsWrapped = true;
        writeTagResponse retVal = base.Invoke<writeTagRequest, writeTagResponse>(info, request);
        return retVal;
    }
    
    public void writeTag()
    {
        writeTagRequest request = new writeTagRequest();
        writeTagResponse response = this.writeTag(request);
    }
    
    private WriteLogResponse WriteLog(WriteLogRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://www.hulisoft.com/RFIDService/IRFIDService/WriteLog";
        info.ExtraTypes = new System.Type[] {
                typeof(object[])};
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://www.hulisoft.com/RFIDService/IRFIDService/WriteLogResponse";
        info.ResponseIsWrapped = true;
        WriteLogResponse retVal = base.Invoke<WriteLogRequest, WriteLogResponse>(info, request);
        return retVal;
    }
    
    public void WriteLog(object[] parms)
    {
        WriteLogRequest request = new WriteLogRequest(parms);
        WriteLogResponse response = this.WriteLog(request);
    }
    
    private readTagResponse readTag(readTagRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://www.hulisoft.com/RFIDService/IRFIDService/readTag";
        info.ExtraTypes = new System.Type[] {
                typeof(object[])};
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://www.hulisoft.com/RFIDService/IRFIDService/readTagResponse";
        info.ResponseIsWrapped = true;
        readTagResponse retVal = base.Invoke<readTagRequest, readTagResponse>(info, request);
        return retVal;
    }
    
    public void readTag()
    {
        readTagRequest request = new readTagRequest();
        readTagResponse response = this.readTag(request);
    }
    
    private getModuleInfoResponse getModuleInfo(getModuleInfoRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://www.hulisoft.com/RFIDService/IRFIDService/getModuleInfo";
        info.ExtraTypes = new System.Type[] {
                typeof(object[])};
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://www.hulisoft.com/RFIDService/IRFIDService/getModuleInfoResponse";
        info.ResponseIsWrapped = true;
        getModuleInfoResponse retVal = base.Invoke<getModuleInfoRequest, getModuleInfoResponse>(info, request);
        return retVal;
    }
    
    public ModuleInfo getModuleInfo(object[] parms)
    {
        getModuleInfoRequest request = new getModuleInfoRequest(parms);
        getModuleInfoResponse response = this.getModuleInfo(request);
        return response.getModuleInfoResult;
    }
    
    public static System.ServiceModel.Channels.Binding CreateDefaultBinding()
    {
        System.ServiceModel.Channels.CustomBinding binding = new System.ServiceModel.Channels.CustomBinding();
        binding.Elements.Add(new System.ServiceModel.Channels.TextMessageEncodingBindingElement(System.ServiceModel.Channels.MessageVersion.Soap11, System.Text.Encoding.UTF8));
        binding.Elements.Add(new System.ServiceModel.Channels.HttpTransportBindingElement());
        return binding;
    }
    
    private void addProtectionRequirements(System.ServiceModel.Channels.Binding binding)
    {
        if ((IsSecureMessageBinding(binding) == false))
        {
            return;
        }
        System.ServiceModel.Security.ChannelProtectionRequirements cpr = new System.ServiceModel.Security.ChannelProtectionRequirements();
        ApplyProtection("http://www.hulisoft.com/RFIDService/IRFIDService/writeTag", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://www.hulisoft.com/RFIDService/IRFIDService/writeTag", cpr.IncomingEncryptionParts, true);
        ApplyProtection("http://www.hulisoft.com/RFIDService/IRFIDService/WriteLog", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://www.hulisoft.com/RFIDService/IRFIDService/WriteLog", cpr.IncomingEncryptionParts, true);
        ApplyProtection("http://www.hulisoft.com/RFIDService/IRFIDService/readTag", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://www.hulisoft.com/RFIDService/IRFIDService/readTag", cpr.IncomingEncryptionParts, true);
        ApplyProtection("http://www.hulisoft.com/RFIDService/IRFIDService/getModuleInfo", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://www.hulisoft.com/RFIDService/IRFIDService/getModuleInfo", cpr.IncomingEncryptionParts, true);
        if ((binding.MessageVersion.Addressing == System.ServiceModel.Channels.AddressingVersion.None))
        {
            ApplyProtection("*", cpr.OutgoingSignatureParts, true);
            ApplyProtection("*", cpr.OutgoingEncryptionParts, true);
        }
        else
        {
            ApplyProtection("http://www.hulisoft.com/RFIDService/IRFIDService/writeTagResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://www.hulisoft.com/RFIDService/IRFIDService/writeTagResponse", cpr.OutgoingEncryptionParts, true);
            ApplyProtection("http://www.hulisoft.com/RFIDService/IRFIDService/WriteLogResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://www.hulisoft.com/RFIDService/IRFIDService/WriteLogResponse", cpr.OutgoingEncryptionParts, true);
            ApplyProtection("http://www.hulisoft.com/RFIDService/IRFIDService/readTagResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://www.hulisoft.com/RFIDService/IRFIDService/readTagResponse", cpr.OutgoingEncryptionParts, true);
            ApplyProtection("http://www.hulisoft.com/RFIDService/IRFIDService/getModuleInfoResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://www.hulisoft.com/RFIDService/IRFIDService/getModuleInfoResponse", cpr.OutgoingEncryptionParts, true);
        }
        this.Parameters.Add(cpr);
    }
}
